/*{"mac":"1:62eeb063befc3867ae76a8b86e45da42c0a5fe7c6e5244a456a1bd89da10c39d","k":"1.6.4","version":"20477185","created":"2013-09-23T19:52:07Z"}*/
/*
 * For font license information, see the CSS file loaded by this JavaScript.
 */
;(function(window,document,undefined){
var h=!0,k=null,l=!1;function m(a){return function(){return this[a]}}var aa=this;function ca(a,b){var c=a.split("."),d=aa;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&void 0!==b?d[e]=b:d=d[e]?d[e]:d[e]={}}function da(a,b,c){return a.call.apply(a.bind,arguments)}
function ea(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function n(a,b,c){n=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?da:ea;return n.apply(k,arguments)}var fa=Date.now||function(){return+new Date};
function q(a,b){this.Y=a;this.P=b||a;this.F=this.P.document}q.prototype.createElement=function(a,b,c){a=this.F.createElement(a);if(b)for(var d in b)b.hasOwnProperty(d)&&("style"==d?a.style.cssText=b[d]:a.setAttribute(d,b[d]));c&&a.appendChild(this.F.createTextNode(c));return a};function r(a,b,c){a=a.F.getElementsByTagName(b)[0];a||(a=document.documentElement);a&&a.lastChild&&a.insertBefore(c,a.lastChild)}function ga(a,b){function c(){a.F.body?b():setTimeout(c,0)}c()}
function s(a,b){for(var c=a.className.split(/\s+/),d=0,e=c.length;d<e;d++)if(c[d]==b)return;c.push(b);a.className=c.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}function t(a,b){for(var c=a.className.split(/\s+/),d=[],e=0,f=c.length;e<f;e++)c[e]!=b&&d.push(c[e]);a.className=d.join(" ").replace(/\s+/g," ").replace(/^\s+|\s+$/,"")}function ha(a,b){for(var c=a.className.split(/\s+/),d=0,e=c.length;d<e;d++)if(c[d]==b)return h;return l}
function ia(a){var b=a.P.location.protocol;"about:"==b&&(b=a.Y.location.protocol);return"https:"==b?"https:":"http:"}
function ja(a,b,c){var d=a.F.getElementsByTagName("head")[0];if(d){var e=a.createElement("script",{src:b}),f=l;e.onload=e.onreadystatechange=function(){if(!f&&(!this.readyState||"loaded"==this.readyState||"complete"==this.readyState))f=h,c&&c(k),e.onload=e.onreadystatechange=k,"HEAD"==e.parentNode.tagName&&d.removeChild(e)};d.appendChild(e);window.setTimeout(function(){f||(f=h,c&&c(Error("Script load timeout")))},5E3)}}function u(a,b,c){this.Na=a;this.aa=b;this.Ma=c}
ca("internalWebfont.BrowserInfo",u);u.prototype.Aa=m("Na");u.prototype.hasWebFontSupport=u.prototype.Aa;u.prototype.Ba=m("aa");u.prototype.hasWebKitFallbackBug=u.prototype.Ba;u.prototype.Ca=m("Ma");u.prototype.hasWebKitMetricsBug=u.prototype.Ca;function v(a,b,c,d){this.e=a!=k?a:k;this.m=b!=k?b:k;this.D=c!=k?c:k;this.j=d!=k?d:k}var ka=/^([0-9]+)(?:[\._-]([0-9]+))?(?:[\._-]([0-9]+))?(?:[\._+-]?(.*))?$/;
function w(a,b){return a.e>b.e||a.e===b.e&&a.m>b.m||a.e===b.e&&a.m===b.m&&a.D>b.D?1:a.e<b.e||a.e===b.e&&a.m<b.m||a.e===b.e&&a.m===b.m&&a.D<b.D?-1:0}function x(a,b){return 0===w(a,b)||1===w(a,b)}v.prototype.toString=function(){return[this.e,this.m||"",this.D||"",this.j||""].join("")};
function z(a){a=ka.exec(a);var b=k,c=k,d=k,e=k;a&&(a[1]!==k&&a[1]&&(b=parseInt(a[1],10)),a[2]!==k&&a[2]&&(c=parseInt(a[2],10)),a[3]!==k&&a[3]&&(d=parseInt(a[3],10)),a[4]!==k&&a[4]&&(e=/^[0-9]+$/.test(a[4])?parseInt(a[4],10):a[4]));return new v(b,c,d,e)}function B(a,b,c,d,e,f,g,j,p,y,ba){this.Q=a;this.n=b;this.La=c;this.u=d;this.A=e;this.qa=f;this.k=g;this.h=j;this.Ha=p;this.N=y;this.t=ba}ca("internalWebfont.UserAgent",B);B.prototype.getName=m("Q");B.prototype.getName=B.prototype.getName;
B.prototype.za=m("La");B.prototype.getVersion=B.prototype.za;B.prototype.va=m("u");B.prototype.getEngine=B.prototype.va;B.prototype.wa=m("qa");B.prototype.getEngineVersion=B.prototype.wa;B.prototype.xa=m("k");B.prototype.getPlatform=B.prototype.xa;B.prototype.ya=m("Ha");B.prototype.getPlatformVersion=B.prototype.ya;B.prototype.ua=m("N");B.prototype.getDocumentMode=B.prototype.ua;B.prototype.ta=m("t");B.prototype.getBrowserInfo=B.prototype.ta;function na(a,b){this.c=a;this.M=b}
var oa=new B("Unknown",new v,"Unknown","Unknown",new v,"Unknown","Unknown",new v,"Unknown",void 0,new u(l,l,l));
na.prototype.parse=function(){var a;if(-1!=this.c.indexOf("MSIE")||-1!=this.c.indexOf("Trident/")){a=C(this);var b=D(this),c=z(b),d=k,e=k,f=k,g=k,j=E(this.c,/Trident\/([\d\w\.]+)/,1),p=F(this.M),d=-1!=this.c.indexOf("MSIE")?E(this.c,/MSIE ([\d\w\.]+)/,1):E(this.c,/rv:([\d\w\.]+)/,1),e=z(d);""!=j?(f="Trident",g=z(j)):(f="Unknown",g=new v,j="Unknown");a=new B("MSIE",e,d,f,g,j,a,c,b,p,new u("Windows"==a&&6<=e.e||"Windows Phone"==a&&8<=c.e,l,l))}else if(-1!=this.c.indexOf("Opera"))a:if(a="Unknown",b=
E(this.c,/Presto\/([\d\w\.]+)/,1),c=z(b),d=D(this),e=z(d),f=F(this.M),c.e!==k?a="Presto":(-1!=this.c.indexOf("Gecko")&&(a="Gecko"),b=E(this.c,/rv:([^\)]+)/,1),c=z(b)),-1!=this.c.indexOf("Opera Mini/"))g=E(this.c,/Opera Mini\/([\d\.]+)/,1),j=z(g),a=new B("OperaMini",j,g,a,c,b,C(this),e,d,f,new u(l,l,l));else{if(-1!=this.c.indexOf("Version/")&&(g=E(this.c,/Version\/([\d\.]+)/,1),j=z(g),j.e!==k)){a=new B("Opera",j,g,a,c,b,C(this),e,d,f,new u(10<=j.e,l,l));break a}g=E(this.c,/Opera[\/ ]([\d\.]+)/,1);
j=z(g);a=j.e!==k?new B("Opera",j,g,a,c,b,C(this),e,d,f,new u(10<=j.e,l,l)):new B("Opera",new v,"Unknown",a,c,b,C(this),e,d,f,new u(l,l,l))}else/OPR\/[\d.]+/.test(this.c)?a=pa(this):/AppleWeb(K|k)it/.test(this.c)?a=pa(this):-1!=this.c.indexOf("Gecko")?(a="Unknown",b=new v,c="Unknown",d=D(this),e=z(d),f=l,-1!=this.c.indexOf("Firefox")?(a="Firefox",c=E(this.c,/Firefox\/([\d\w\.]+)/,1),b=z(c),f=3<=b.e&&5<=b.m):-1!=this.c.indexOf("Mozilla")&&(a="Mozilla"),g=E(this.c,/rv:([^\)]+)/,1),j=z(g),f||(f=1<j.e||
1==j.e&&9<j.m||1==j.e&&9==j.m&&2<=j.D||g.match(/1\.9\.1b[123]/)!=k||g.match(/1\.9\.1\.[\d\.]+/)!=k),a=new B(a,b,c,"Gecko",j,g,C(this),e,d,F(this.M),new u(f,l,l))):a=oa;return a};function C(a){var b=E(a.c,/(iPod|iPad|iPhone|Android|Windows Phone|BB\d{2}|BlackBerry)/,1);if(""!=b)return/BB\d{2}/.test(b)&&(b="BlackBerry"),b;a=E(a.c,/(Linux|Mac_PowerPC|Macintosh|Windows|CrOS)/,1);return""!=a?("Mac_PowerPC"==a&&(a="Macintosh"),a):"Unknown"}
function D(a){var b=E(a.c,/(OS X|Windows NT|Android) ([^;)]+)/,2);if(b||(b=E(a.c,/Windows Phone( OS)? ([^;)]+)/,2))||(b=E(a.c,/(iPhone )?OS ([\d_]+)/,2)))return b;if(b=E(a.c,/(?:Linux|CrOS) ([^;)]+)/,1))for(var b=b.split(/\s/),c=0;c<b.length;c+=1)if(/^[\d\._]+$/.test(b[c]))return b[c];return(a=E(a.c,/(BB\d{2}|BlackBerry).*?Version\/([^\s]*)/,2))?a:"Unknown"}
function pa(a){var b=C(a),c=D(a),d=z(c),e=E(a.c,/AppleWeb(?:K|k)it\/([\d\.\+]+)/,1),f=z(e),g="Unknown",j=new v,p="Unknown",y=l;/OPR\/[\d.]+/.test(a.c)?g="Opera":-1!=a.c.indexOf("Chrome")||-1!=a.c.indexOf("CrMo")||-1!=a.c.indexOf("CriOS")?g="Chrome":/Silk\/\d/.test(a.c)?g="Silk":"BlackBerry"==b||"Android"==b?g="BuiltinBrowser":-1!=a.c.indexOf("PhantomJS")?g="PhantomJS":-1!=a.c.indexOf("Safari")?g="Safari":-1!=a.c.indexOf("AdobeAIR")&&(g="AdobeAIR");"BuiltinBrowser"==g?p="Unknown":"Silk"==g?p=E(a.c,
/Silk\/([\d\._]+)/,1):"Chrome"==g?p=E(a.c,/(Chrome|CrMo|CriOS)\/([\d\.]+)/,2):-1!=a.c.indexOf("Version/")?p=E(a.c,/Version\/([\d\.\w]+)/,1):"AdobeAIR"==g?p=E(a.c,/AdobeAIR\/([\d\.]+)/,1):"Opera"==g?p=E(a.c,/OPR\/([\d.]+)/,1):"PhantomJS"==g&&(p=E(a.c,/PhantomJS\/([\d.]+)/,1));j=z(p);y="AdobeAIR"==g?2<j.e||2==j.e&&5<=j.m:"BlackBerry"==b?10<=d.e:"Android"==b?2<d.e||2==d.e&&1<d.m:526<=f.e||525<=f.e&&13<=f.m;return new B(g,j,p,"AppleWebKit",f,e,b,d,c,F(a.M),new u(y,536>f.e||536==f.e&&11>f.m,"iPhone"==
b||"iPad"==b||"iPod"==b||"Macintosh"==b))}function E(a,b,c){return(a=a.match(b))&&a[c]?a[c]:""}function F(a){if(a.documentMode)return a.documentMode}function qa(a){this.Fa=a||"-"}qa.prototype.j=function(a){for(var b=[],c=0;c<arguments.length;c++)b.push(arguments[c].replace(/[\W_]+/g,"").toLowerCase());return b.join(this.Fa)};function ra(a,b,c){this.g=a;this.l=b;this.T=c;this.q="wf";this.o=new qa("-")}
function sa(a){t(a.l,a.o.j(a.q,"loading"));ha(a.l,a.o.j(a.q,"active"))||s(a.l,a.o.j(a.q,"inactive"));G(a,"inactive")}function G(a,b,c){if(a.T[b])if(c)a.T[b](c.getName(),I(c));else a.T[b]()}function J(a,b){this.Q=a;this.ba=4;this.R="n";var c=(b||"n4").match(/^([nio])([1-9])$/i);c&&(this.R=c[1],this.ba=parseInt(c[2],10))}J.prototype.getName=m("Q");function I(a){return a.R+a.ba}function K(a,b){this.g=a;this.J=b;this.z=this.g.createElement("span",{"aria-hidden":"true"},this.J)}
function ta(a,b){var c;c=[];for(var d=b.Q.split(/,\s*/),e=0;e<d.length;e++){var f=d[e].replace(/['"]/g,"");-1==f.indexOf(" ")?c.push(f):c.push("'"+f+"'")}c=c.join(",");d="normal";e=b.ba+"00";"o"===b.R?d="oblique":"i"===b.R&&(d="italic");a.z.style.cssText="position:absolute;top:-999px;left:-999px;font-size:300px;width:auto;height:auto;line-height:normal;margin:0;padding:0;font-variant:normal;white-space:nowrap;font-family:"+c+";"+("font-style:"+d+";font-weight:"+e+";")}
function ua(a){r(a.g,"body",a.z)}K.prototype.remove=function(){var a=this.z;a.parentNode&&a.parentNode.removeChild(a)};function va(a,b,c,d,e,f,g,j){this.ca=a;this.Da=b;this.g=c;this.v=d;this.J=j||"BESbswy";this.t=e;this.K={};this.Z=f||5E3;this.ka=g||k;this.I=this.H=k;a=new K(this.g,this.J);ua(a);for(var p in L)L.hasOwnProperty(p)&&(ta(a,new J(L[p],I(this.v))),this.K[L[p]]=a.z.offsetWidth);a.remove()}var L={Ua:"serif",Ta:"sans-serif",Qa:"monospace"};
va.prototype.start=function(){this.H=new K(this.g,this.J);ua(this.H);this.I=new K(this.g,this.J);ua(this.I);this.Ja=fa();ta(this.H,new J(this.v.getName()+",serif",I(this.v)));ta(this.I,new J(this.v.getName()+",sans-serif",I(this.v)));wa(this)};function xa(a,b,c){for(var d in L)if(L.hasOwnProperty(d)&&b===a.K[L[d]]&&c===a.K[L[d]])return h;return l}
function wa(a){var b=a.H.z.offsetWidth,c=a.I.z.offsetWidth;b===a.K.serif&&c===a.K["sans-serif"]||a.t.aa&&xa(a,b,c)?fa()-a.Ja>=a.Z?a.t.aa&&xa(a,b,c)&&(a.ka===k||a.ka.hasOwnProperty(a.v.getName()))?ya(a,a.ca):ya(a,a.Da):setTimeout(n(function(){wa(this)},a),25):ya(a,a.ca)}function ya(a,b){a.H.remove();a.I.remove();b(a.v)}function M(a,b,c,d){this.g=b;this.B=c;this.V=0;this.na=this.ja=l;this.Z=d;this.t=a.t}
M.prototype.$=function(a,b,c,d){if(0===a.length&&d)sa(this.B);else{this.V+=a.length;d&&(this.ja=d);for(d=0;d<a.length;d++){var e=a[d],f=b[e.getName()],g=this.B,j=e;s(g.l,g.o.j(g.q,j.getName(),I(j).toString(),"loading"));G(g,"fontloading",j);(new va(n(this.ra,this),n(this.sa,this),this.g,e,this.t,this.Z,c,f)).start()}}};
M.prototype.ra=function(a){var b=this.B;t(b.l,b.o.j(b.q,a.getName(),I(a).toString(),"loading"));t(b.l,b.o.j(b.q,a.getName(),I(a).toString(),"inactive"));s(b.l,b.o.j(b.q,a.getName(),I(a).toString(),"active"));G(b,"fontactive",a);this.na=h;za(this)};M.prototype.sa=function(a){var b=this.B;t(b.l,b.o.j(b.q,a.getName(),I(a).toString(),"loading"));ha(b.l,b.o.j(b.q,a.getName(),I(a).toString(),"active"))||s(b.l,b.o.j(b.q,a.getName(),I(a).toString(),"inactive"));G(b,"fontinactive",a);za(this)};
function za(a){0==--a.V&&a.ja&&(a.na?(a=a.B,t(a.l,a.o.j(a.q,"loading")),t(a.l,a.o.j(a.q,"inactive")),s(a.l,a.o.j(a.q,"active")),G(a,"active")):sa(a.B))}function Aa(a,b){this.Ia=a;this.fa=b}function Ba(a){for(var b=a.Ia.join(","),c=[],d=0;d<a.fa.length;d++){var e=a.fa[d];c.push(e.name+":"+e.value+";")}return b+"{"+c.join("")+"}"}function Ca(a){this.g=a}Ca.prototype.toString=function(){return encodeURIComponent(this.g.P.location.hostname||this.g.Y.location.hostname)};
function Da(a,b){this.r=a;this.p=b}Da.prototype.toString=function(){for(var a=[],b=0;b<this.p.length;b++)for(var c=this.p[b],d=c.C(),c=c.C(this.r),e=0;e<d.length;e++){var f;a:{for(f=0;f<c.length;f++)if(d[e]===c[f]){f=h;break a}f=l}a.push(f?1:0)}a=a.join("");a=a.replace(/^0+/,"");b=[];for(d=a.length;0<d;d-=4)c=a.slice(0>d-4?0:d-4,d),b.unshift(parseInt(c,2).toString(16));return b.join("")};function N(a){this.Ka=a}
N.prototype.j=function(a,b){var c=b||{},d=this.Ka.replace(/\{\/?([^*}]*)(\*?)\}/g,function(a,b,d){return d&&c[b]?"/"+c[b].join("/"):c[b]||""});d.match(/^\/\//)&&(d=(a?"https:":"http:")+d);return d.replace(/\/*\?*($|\?)/,"$1")};function O(a,b,c,d){this.G=a;this.O=b;this.Xa=c;this.Ya=d;this.ha={};this.ga={}}O.prototype.C=function(a){return a?(this.ha[a]||this.O).slice(0):this.O.slice(0)};O.prototype.$=function(a,b,c){var d=[],e={};Ea(this,b,d,e);a(d,e,c)};
function Ea(a,b,c,d){c.push(a.G);d[a.G]=a.C(b);a=a.ga[b]||[];for(b=0;b<a.length;b++){for(var e=a[b],f=e.G,g=l,j=0;j<c.length;j++)c[j]==f&&(g=h);g||(c.push(f),d[f]=e.C())}}function Fa(a,b){this.G=a;this.O=b}Fa.prototype.C=m("O");function Ga(){this.pa=this.Oa=this.L=this.W=this.Ea=h}function P(a){return"Windows"===a.k}function R(a){return P(a)&&0===w(a.h,new v(5,1))||P(a)&&0===w(a.h,new v(5,2))||P(a)&&0===w(a.h,new v(6,0))||P(a)&&x(a.h,new v(6,1))}
function S(a){return"Macintosh"===a.k&&(x(a.h,new v(10,4))||a.h.e===k)}function Ha(a,b){return b.Ea&&("iPhone"===a.k||"iPod"===a.k)}function Ia(a,b){return Ha(a,b)&&x(a.h,new v(4,2))&&-1===w(a.h,new v(5))}function Ja(a,b){return b.W&&"iPad"===a.k&&x(a.h,new v(4,2))&&-1===w(a.h,new v(5))}function T(a,b){return b.L&&"Android"===a.k}function Ka(a,b){return T(a,b)&&x(a.h,new v(2,2))&&-1===w(a.h,new v(3,1))}function La(a,b){return T(a,b)&&x(a.h,new v(3,1))&&-1===w(a.h,new v(4,1))}
function U(a){return"Linux"===a.k||"Ubuntu"===a.k}function Ma(a){return"Gecko"===a.u&&0===w(a.A,new v(1,9,1))&&!/^b[1-3]$/.test(a.A.j||"")}function Na(a){return"Safari"===a.getName()&&"AppleWebKit"===a.u||"Unknown"===a.getName()&&"AppleWebKit"===a.u&&("iPhone"===a.k||"iPad"===a.k||"iPod"===a.k)}function Oa(a){return"Safari"===a.getName()&&"AppleWebKit"===a.u&&x(a.A,new v(525,13))&&-1===w(a.A,new v(534,50))}function Pa(a){return"Opera"===a.getName()&&x(a.n,new v(10,54))&&-1===w(a.n,new v(11,10))}
function Qa(a){return"BuiltinBrowser"===a.getName()}function Ra(a){this.ma=a}function Sa(a,b){return b}
var Ta={Ra:"a",Sa:"b",Wa:"d",Va:"f",Pa:"i"},Ua={a:function(a,b){return Oa(a)&&R(a)||Qa(a)&&(Ka(a,b)||T(a,b)&&x(a.h,new v(4,1)))||b.L&&"Silk"===a.getName()&&-1===w(a.n,new v(2))&&(Ka(a,b)||S)||b.L&&"Silk"===a.getName()&&x(a.n,new v(2))&&T(a,b)&&x(a.h,new v(4,1))||Na(a)&&(Ja(a,b)||Ia(a,b))||Ma(a)&&(R(a)||U(a))||Pa(a)&&(R(a)||U(a))||("Chrome"===a.getName()&&1===w(a.n,new v(4,0,249))&&-1===w(a.n,new v(6))||0===w(a.n,new v(4,0,249))&&(a.n.j===k||4<=a.n.j))&&(R(a)||U(a)||S(a))||"Chrome"===a.getName()&&
x(a.n,new v(6))&&(Ja(a,b)||Ia(a,b))||"AdobeAIR"===a.getName()&&x(a.n,new v(2,5))&&(P(a)&&a.h.e===k||U(a))},b:function(a){return Ma(a)&&S(a)||Oa(a)&&S(a)||Pa(a)&&S(a)||"AdobeAIR"===a.getName()&&x(a.n,new v(2,5))&&S(a)},d:function(a,b){return"Chrome"===a.getName()&&x(a.n,new v(6))&&(R(a)||U(a)||S(a)||T(a,b)||"CrOS"===a.k||b.W&&"iPad"===a.k&&x(a.h,new v(5))||Ha(a,b)&&x(a.h,new v(5)))||"Gecko"===a.u&&1===w(a.A,new v(1,9,1))&&(R(a)||U(a)||S(a)||T(a,b))||"Safari"===a.getName()&&("AppleWebKit"===a.u&&x(a.A,
new v(534,50)))&&(R(a)||S(a))||Na(a)&&(b.W&&"iPad"===a.k&&x(a.h,new v(5))||Ha(a,b)&&x(a.h,new v(5)))||"Opera"===a.getName()&&x(a.n,new v(11,10))&&(R(a)||U(a)||S(a)||T(a,b))||"MSIE"===a.getName()&&9<=a.N&&(P(a)&&x(a.h,new v(6,1))||P(a)&&0===w(a.h,new v(6,0)))||"MSIE"===a.getName()&&b.Oa&&"Windows Phone"===a.k&&x(a.h,new v(8))||Qa(a)&&b.pa&&"BlackBerry"===a.k&&x(a.h,new v(10))},f:function(a,b){return Qa(a)&&La(a,b)||b.L&&"Silk"===a.getName()&&x(a.n,new v(2))&&(La(a,b)||U(a))},i:function(a){return"MSIE"===
a.getName()&&(x(a.n,new v(6,0))&&(void 0===a.N||9>a.N))&&R(a)}};function Va(a,b){var c=b||new Ga,d;for(d in Ta){var e=Ta[d];if(Ua[e](a,c))return e}return k}var Wa={};
Wa.i=new Ra(function(a,b,c){for(var d=0;d<b.length;d+=1){var e=b[d],f=a.replace(/(-1|-2)$/,"").slice(0,28)+"-"+e;c.push(new Fa(f,[e]))}a={};for(e=0;e<b.length;e++)c=b[e],d=c.charAt(1),(a[d]||(a[d]=[])).push(c);c=[[4,3,2,1,5,6,7,8,9],[7,8,9,6,5,4,3,2,1]];d=[];for(e=0;e<c.length;e++)for(var f=c[e],g=0;g<f.length;g++){var j=f[g];if(a[j]){d=d.concat(a[j]);break}}c=d;d={};a=[];for(e=0;e<c.length;e++)f=c[e],d[f]||(d[f]=h,a.push(f));c=[];for(d=0;d<b.length;d++){e=b[d];for(f=0;f<a.length;f++)g=a[f],g==e&&
c.push(g)}return c});var V={};V.a=V.b=V.d=function(){return[]};V.f=function(a){return[new Ca(a)]};V.i=function(a,b,c){return[new Ca(a),new Da(b,c)]};function W(a){this.g=a;this.ea=this.c=this.r=k;this.p=[];this.w=[];this.oa=this.U=k}W.prototype.supportsConfiguredBrowser=function(){return!!this.r};
W.prototype.init=function(){if(0<this.w.length){for(var a=[],b=0;b<this.w.length;b++)a.push(Ba(this.w[b]));var b=this.g,a=a.join(""),c=this.g.createElement("style");c.setAttribute("type","text/css");c.styleSheet?c.styleSheet.cssText=a:c.appendChild(document.createTextNode(a));r(b,"head",c)}};
W.prototype.load=function(a,b){if(this.r){for(var c=Wa[this.r]||new Ra(Sa),d=0;d<this.p.length;d++){for(var e=this.p[d],f=this.r,g=c,j=[],p=e.G.split(",")[0].replace(/"|'/g,""),y=e.C(),ba=j,A=void 0,Q=[],H={},la=0;la<y.length;la++)A=y[la],0<A.length&&!H[A]&&(H[A]=h,Q.push(A));y=Q;g=g.ma?g.ma(p,y,ba):y;e.ha[f]=g;e.ga[f]=j}if(this.U){c=V[this.r](this.g,this.r,this.p);d=this.r;e=[];for(f=0;f<c.length;f++)e.push(c[f].toString());var d=this.U.j("https:"===ia(this.g),{format:d,extras:e}),c=this.g,d=c.createElement("link",
{rel:"stylesheet",href:d}),X=l;d.onload=function(){X||(X=h)};d.onerror=function(){X||(X=h)};r(c,"head",d)}if(a){var ma=this,db=this.r;ga(this.g,function(){for(var c=0;c<ma.p.length;c++)ma.p[c].$(a,db,b&&c==ma.p.length-1)})}}};W.prototype.collectFontFamilies=function(a,b){if(this.r)for(var c=0;c<this.p.length;c++)Ea(this.p[c],this.r,a,b)};
W.prototype.performOptionalActions=function(){if(this.X){var a=this,b=this.c,c=this.g;ga(this.g,function(){var d=a.X;if(d.la){var e=window.__adobewebfontsappname__,e=e?e.toString().substr(0,20):"",d=d.la.j("https:"===ia(c),{host:encodeURIComponent(c.P.location.hostname||c.Y.location.hostname),app:encodeURIComponent(e),_:(+new Date).toString()}),f=new Image(1,1);f.src=d;f.onload=function(){f.onload=k}}d=a.X;d.da&&(d=d.da.j(b,c),r(c,"body",d))})}};
function Xa(a,b,c,d){this.Ga=a;this.g=b;this.c=c;this.l=d;this.s=[]}Xa.prototype.S=function(a){this.s.push(a)};Xa.prototype.load=function(a,b){var c=a,d=b||{};if("string"==typeof c)c=[c];else if(!c||!c.length)d=c||{},c=[];if(c.length)for(var e=this,f=c.length,g=0;g<c.length;g++){var j=this.Ga.j("https:"===ia(this.g),{id:encodeURIComponent(c[g])});ja(this.g,j,function(){0==--f&&Ya(e,d)})}else Ya(this,d)};
function Ya(a,b){if(0!=a.s.length){for(var c=new ra(a.g,a.l,b),d=l,e=0;e<a.s.length;e++)a.s[e].init(),d=d||a.s[e].supportsConfiguredBrowser();if(d){s(c.l,c.o.j(c.q,"loading"));G(c,"loading");for(var f=new M(a.c,a.g,c),c=function(a,b,c){for(var d=[],e=0;e<a.length;e+=1){var A=a[e];if(b[A])for(var Q=b[A],H=0;H<Q.length;H+=1)d.push(new J(A,Q[H]));else d.push(new J(A))}f.$(d,{},k,c)},d=0;d<a.s.length;d++)e=a.s[d],e.supportsConfiguredBrowser()&&(e.load(c,d==a.s.length-1),e.performOptionalActions(window))}else sa(c);
a.s=[]}}function Za(a){this.ia=a;this.s=[]}Za.prototype.S=function(a){this.s.push(a)};Za.prototype.load=function(){var a=this.ia.__webfonttypekitmodule__;if(a)for(var b=0;b<this.s.length;b++){var c=this.s[b],d=a[c.oa];d&&d(function(a,b,d){a=[];b={};var j=(new na(navigator.userAgent,document)).parse(),p=c;p.c=j;p.r=Va(p.c,p.ea);c.supportsConfiguredBrowser()&&(c.init(),c.load(k),c.collectFontFamilies(a,b),c.performOptionalActions(window));d(c.supportsConfiguredBrowser(),a,b)})}};
var $a=(new na(navigator.userAgent,document)).parse();window.Typekit||(window.Typekit={});if(!window.Typekit.load){var Y=new Xa(new N("//typeface.nytimes.com/{id}.js"),new q(window),$a,document.documentElement),Z=new Za(window);window.Typekit.load=function(){Y.load.apply(Y,arguments)};window.Typekit.addKit=function(){Y.S.apply(Y,arguments)}}var ab=k,bb,$,ab=new N("//p.typekit.net/p.gif?a=82618&f=387.389.391.5478.5479.5480.5481.18469&h={host}&ht=sh&k=miq8eej&s=1&_={_}");
bb=new function(){var a=ab;this.da=k;this.la=a};$=new W(new q(window));$.oa="miq8eej";$.U=new N("//typeface.nytimes.com/k/miq8eej-{format}.css?3bb2a6e53c9684ffdc9a9ef6195b2a62629238bd18c5441a0a7e695279fc8dcc9a3ac48ed26016662d979705c6de658ed19cc862f2bef627bf43f2fe3b7833032309e4a2772618ec26400ee35475cce84ddb3764555d2b4bd3da8032097f4c9437b9bd232e806a659ab3119d45c91b25358af1bebfbdda451d5611e72b4c965612e52897a2c3437e6b7a7bef7aac5959678d87b245f3699e22c33943bd9ef4915c7259ebb2cfd60d742f44829fa3505f80f373271411b6b4bddfa984392aa72be79e2e3745ddcf36c74d923764e12192f3e6a6064cdf5dcf906269aaba84cb1043f801fac01249f917a886892ba213c1d96e39c324a91be4e89f1df0bbce1c886831ecbfabc78f8a849799507abac9ae08932f9ee67e369a6637f6b509ebdaf1a89b7e5e0c09a5e3e4c51bab40baf5b4a47c6d1384f138b36bd935977efd08c5f9869067334e36eeb21c730dfbbcc6424ce137873cb0a2e52a3eb2f1b116f46aea04bc0cdc070796cf74b6446ea1f628def5f43a1e8de6e7d892064743d19bd44fad22ebfa8f888449336ff378ed8e573458f6");
$.X=bb;$.p.push(new O("nyt-cheltenham-hinted",["n5","i5","n7","i7"]));$.p.push(new O("nyt-franklin",["n3","n5","n7"]));$.p.push(new O("nyt-karnak-display-130124",["n4"]));$.w.push(new Aa([".tk-nyt-cheltenham-hinted"],[{value:'"nyt-cheltenham-hinted",georgia,"times new roman",serif',name:"font-family"}]));$.w.push(new Aa([".tk-nyt-franklin"],[{value:'"nyt-franklin",sans-serif',name:"font-family"}]));
$.w.push(new Aa([".tk-nyt-karnak-display-130124"],[{value:'"nyt-karnak-display-130124",sans-serif',name:"font-family"}]));var cb;if(cb=Z)cb=!!Z.ia.__webfonttypekitmodule__;cb?(Z.S($),Z.load()):($.c=$a,$.r=Va($.c,$.ea),window.Typekit.addKit($));
})(this,document);